/* COPYRIGHT (C) 2014 barreiro. All Rights Reserved. */

package net.projecteuler.barreiro.problem;

import static net.projecteuler.barreiro.algorithm.Factorization.numberOfFactors;
import static net.projecteuler.barreiro.algorithm.util.StreamUtils.firstLong;
import static net.projecteuler.barreiro.algorithm.util.StreamUtils.infiniteParallelStream;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p/>
 * Let us list the factors of the first seven triangle numbers: <pre>
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28 </pre>
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p/>
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * @author barreiro
 */
public class Solver012 extends ProjectEulerSolver {

    public Solver012() {
        this(500);
    }

    public Solver012(long n) {
        super(n);
    }

    /* --- */

    public long solve() {
        return firstLong(infiniteParallelStream().map(l -> (l * (l + 1)) / 2).filter(t -> numberOfFactors(t) >= N));
    }

}
