/* COPYRIGHT (C) 2014 barreiro. All Rights Reserved. */

package net.projecteuler.barreiro.problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author barreiro
 */
public class Solver002 extends ProjectEulerSolver {

    public Solver002() {
        this(4000000);
    }

    public Solver002(long n) {
        super(n);
    }

    /* --- */

    public long solve() {
        long sum = 0;
        long f1 = 1, f2 = 1;

        while (f1 + f2 <= N) {
            f2 += f1;
            f1 = f2 - f1;
            if (f2 % 2 == 0) {
                sum += f2;
            }
        }
        return sum;
    }

}
