/* COPYRIGHT (C) 2014 barreiro. All Rights Reserved. */

package net.projecteuler.barreiro.problem;

import net.projecteuler.barreiro.algorithm.util.LongUtils;

import static net.projecteuler.barreiro.algorithm.Fibonacci.fibonacciStream;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author barreiro
 */
public class Solver002 extends ProjectEulerSolver {

    public Solver002() {
        this( 4000000 );
    }

    public Solver002(long n) {
        super( n );
    }

    // --- //

    public long solve() {
        return fibonacciStream( f -> f < N ).filter( LongUtils::isEven ).sum();
    }

}
