[package]
name = "euler"
version = "1.0.0"
edition = "2021"
authors = ["barreiro <lbbbarreiro@gmail.com>"]

[[bin]]
name = "euler"
path = "src/main/rust/euler.rs"

[profile.release]
debug = false
lto = true
codegen-units = 1
overflow-checks = false
panic = "abort"
strip = true
