// COPYRIGHT (C) 2017 barreiro. All Rights Reserved.
// Rust solvers for Project Euler problems

use algorithm::long::{hexagonal, is_pentagonal};
use Solver;

/// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
///
/// Triangle `T(n) = n * (n+1) / 2  -> 1, 3, 6, 10, 15, ...`
/// Pentagonal `P(n) = n * (3*n−1) / 2 -> 1, 5, 12, 22, 35, ...`
/// Hexagonal `H(n) = n * (2*n−1) -> 1, 6, 15, 28, 45, ...`
///
/// It can be verified that `T 285 = P 165 = H 143 = 40755`.
/// Find the next triangle number that is also pentagonal and hexagonal.
pub struct Solver045 {
    pub n: i64
}

impl Default for Solver045 {
    fn default() -> Self {
        Self { n: 144 }
    }
}

#[allow(clippy::maybe_infinite_iter)]
impl Solver for Solver045 {
    fn solve(&self) -> i64 {
        // all hexagonal numbers are also triangle numbers
        (self.n..).map(hexagonal).find(is_pentagonal).unwrap()
    }
}
