/* COPYRIGHT (C) 2014 barreiro. All Rights Reserved. */

package net.projecteuler.barreiro.problem;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author barreiro
 */
public class Problem002Test extends ProjectEulerAbstractTest {

    @Test
    public void test() {
        assertEquals(4613732, new Solver002().solve());
    }

    @Test
    public void minimal() {
        assertEquals(44, new Solver002(100).solve());
    }

}
